#
# Inserts a blank line between shell prompts
add_newline = false

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false

# Use custom format
format = '$username$all'

[username]
style_user = '#32d74b bold'
style_root = '#cc372e bold'
format = '[$user]($style) in '
disabled = false
show_always = true

# Replace the '❯' symbol in the prompt with '➜'
[character]
success_symbol = '❯'
